-- MySQL Script generated by MySQL Workbench
-- Tue Nov 13 10:43:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema air1813
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema air1813
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `air1813` DEFAULT CHARACTER SET utf8 ;
USE `air1813` ;

-- -----------------------------------------------------
-- Table `air1813`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `air1813`.`contact` ;

CREATE TABLE IF NOT EXISTS `air1813`.`contact` (
  `phone_number` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `picture` TEXT NULL,
  PRIMARY KEY (`phone_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `air1813`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `air1813`.`chat` ;

CREATE TABLE IF NOT EXISTS `air1813`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `aes_key` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `air1813`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `air1813`.`member` ;

CREATE TABLE IF NOT EXISTS `air1813`.`member` (
  `user` VARCHAR(16) NOT NULL,
  `chat` INT NOT NULL,
  PRIMARY KEY (`user`, `chat`),
  INDEX `fk_member_user_idx` (`user` ASC) ,
  INDEX `fk_member_chat1_idx` (`chat` ASC) ,
  CONSTRAINT `fk_member_user`
    FOREIGN KEY (`user`)
    REFERENCES `air1813`.`contact` (`phone_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_chat1`
    FOREIGN KEY (`chat`)
    REFERENCES `air1813`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `air1813`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `air1813`.`message` ;

CREATE TABLE IF NOT EXISTS `air1813`.`message` (
  `sender` VARCHAR(16) NOT NULL,
  `chat` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `contents` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT 'Encrypted with AES\nEncoded with base64\nSigned with sender\'s private key',
  PRIMARY KEY (`sender`, `chat`, `timestamp`),
  INDEX `fk_message_user1_idx` (`sender` ASC) ,
  INDEX `fk_message_chat1_idx` (`chat` ASC) ,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`sender`)
    REFERENCES `air1813`.`contact` (`phone_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat`)
    REFERENCES `air1813`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `air1813`;

DELIMITER $$

USE `air1813`$$
DROP TRIGGER IF EXISTS `air1813`.`user_BEFORE_INSERT` $$
USE `air1813`$$
CREATE DEFINER = CURRENT_USER TRIGGER `air1813`.`user_BEFORE_INSERT` BEFORE INSERT ON `user` FOR EACH ROW
BEGIN
	IF NOT (NEW.phone_number REGEXP '^[0-9]+$') THEN
		SIGNAL SQLSTATE '45000'
		SET message_text = 'Phone number can only contain digits.';
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
